apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-event-test-producer-to
  namespace: min-side
  labels:
    team: min-side
spec:
  image: "{{ version }}"
  port: 8080
  liveness:
    path: /isalive
    initialDelay: 30
  readiness:
    path: /isready
    initialDelay: 5
  secureLogs:
    enabled: true
  leaderElection: true
  ingresses:
    - "https://www.ansatt.dev.nav.no/tms-event-test-producer-to"
    - "https://tms-etp.ansatt.dev.nav.no"
  kafka:
    pool: nav-dev
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level3
  accessPolicy:
    outbound:
      rules:
        - application: tms-soknadskvittering
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: "20m"
      memory: 256Mi
  env:
    - name: NAV_DECORATOREN_URL
      value: https://dekoratoren.ekstern.dev.nav.no
    - name: SOKNADSKVITTERING_CLIENT_ID
      value: dev-gcp:min-side:tms-soknadskvittering